version: '3'

tasks:
  start:
    desc: Start the backend in developer mode
    cmds:
      - docker-compose -p cps_backend -f dev.docker-compose.yml up

  end:
    desc: Stop the backend in developer mode
    cmds:
      - docker-compose -p cps_backend -f dev.docker-compose.yml down

  console:
    desc: Open console in (developer mode) running backend
    cmds:
      - docker exec -it cps_backend bash

  wire:
    desc: Generate new compile-time dependency injection file, called `wire_gen.go`, which is needed by our app.
    cmds:
      - go run github.com/google/wire/cmd/wire

  clean:
    cmds:
      - go clean -cache
      - go clean -modcache

  deploy:
    desc: The following `task` will build our project's containers and push them to the public registry
    cmds:
      - docker build -f ./Dockerfile -t rodolfossp/cps-backend:latest --platform linux/amd64 .
      - docker tag rodolfossp/cps-backend:latest rodolfossp/cps-backend:latest
      - docker push rodolfossp/cps-backend:latest
